export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';

export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const UPDATE_AUTH_STATE = 'UPDATE_AUTH_STATE';
