export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';

export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const START_FETCHING_TRANSACTIONS = 'START_FETCHING_TRANSACTIONS';
export const END_FETCHING_TRANSACTIONS = 'END_FETCHING_TRANSACTIONS';

export const FETCH_TRANSACTIONS_PAGES = 'FETCH_TRANSACTIONS_COUNT';
export const START_FETCHING_TRANSACTIONS_PAGES = 'START_FETCHING_TRANSACTIONS_PAGES';
export const END_FETCHING_TRANSACTIONS_PAGES = 'END_FETCHING_TRANSACTIONS_PAGES';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const ADD_ACCOUNTS = 'ADD_ACCOUNTS';
export const EDIT_ACCOUNTS = 'EDIT_ACCOUNTS';
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';

export const UPDATE_AUTH_STATE = 'UPDATE_AUTH_STATE';
