export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_TRANSACTIONS_PAGES = 'FETCH_TRANSACTIONS_COUNT';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const ADD_ACCOUNTS = 'ADD_ACCOUNTS';
export const EDIT_ACCOUNTS = 'EDIT_ACCOUNTS';
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';

export const UPDATE_AUTH_STATE = 'UPDATE_AUTH_STATE';
